---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    attributes:
      java:
        jdk_version: 7
  - name: centos-7.1
    attributes:
      java:
        jdk_version: 7

suites:
  - name: default
    run_list:
      - recipe[java::default]
      - recipe[jmxtrans::default]
    attributes:
      # platform_family: 'rhel'
