source 'https://rubygems.org'
ruby '2.2.0'

gem 'berkshelf'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'rubocop'
gem 'rake'
gem 'foodcritic' # , '= 6.3.0'
gem 'chefspec'
gem 'rspec'
gem 'chef' # , '= 12.0.0'
